### ISSUE TITLE
Prepare app for deployment

### ISSUE THREAD

**Issue by brendon21c** [brendon21c/lmn#2]
Replace database with production database e.g. RDS
Configuration etc. for AWS (or other PaaS) 
Deploy ASAP; deploy updates and new features as soon as they are ready (like they work and have tests)

**Comment by brendon21c** [comment]
I started looking into AWS for this, but was hating it, so I've started going through the tutorials for Heroku to see if that will be a viable solution.

**Comment by marie8bit** [comment]
Would it be viable to ditch postgres, go with sql lite and use python anywhere?

On Mar 30, 2017 4:03 PM, Brendon McKeever <notifications@github.com> wrote:

I started looking into AWS for this, but was hating it, so I've started going through the tutorials for Heroku to see if that will be a viable solution.

**Comment by brendon21c** [comment]
Not really, postgres works well with deployments and plays really nicely with Django which in turn works with a lot of Web hosts. I have looked into heroku and I believe it will work for us, I built their hello world app and deployed it and will continue to work with it tonight in regards to postgres. The only real issue is that only one person can deploy to the server, so what we would do is write code, push to github and then have myself, or a person we designate, deploy when the new feature is ready.
Brendon 
-------- Original message --------From: marie8bit <notifications@github.com> Date: 3/30/17  4:09 PM  (GMT-06:00) To: brendon21c/lmn <lmn@noreply.github.com> Cc: Brendon McKeever <brennon.mckeever@gmail.com>, Assign <assign@noreply.github.com> Subject: Re: [brendon21c/lmn] Prepare app for deployment (#2) 
Would it be viable to ditch postgres, go with sql lite and use python anywhere?





On Mar 30, 2017 4:03 PM, Brendon McKeever <notifications@github.com> wrote:





I started looking into AWS for this, but was hating it, so I've started going through the tutorials for Heroku to see if that will be a viable solution.

**Comment by brendon21c** [comment]
I have gone through every article I can find on Heroku and have managed to successfully configure and deploy the djangogirls program (with help from several articles) to Heroku and everything is working as it should. I am going to ask Clara some questions tomorrow to clarify a few things, but I think I have enough to be able to deploy our app. Sorry for the delay.

**Comment by mo12g13** [comment]
Thanks for what you have done so far. Well appreciated.

**Comment by brendon21c** [comment]
I have gotten deployment working and up to date with the current application. You will need to create a user if you want to use it. 

salty-wave-34667.herokuapp.com
